---
title: "Acerbi2023"
output: html_document
date: "2025-04-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# måde at udregne power!
crit <- function(H0, M, p){
  crit <- numeric(1)
crit<- H0[floor(M*p)]
}
M <- 10^5
p <- 0.108

length(f3Test2_H2[f3Test2_H2<sort(f3Test2_H0)[floor(M*p)]])/M
```

# Figur 1: ES(F)=ES(P)

```{r}
p <- 0.05      
T <- 250       
N <- 10^5     
alpha <- 0.025 
ES <- -integrate(function(q) qnorm(q, 0, 1), lower = 0, upper = alpha)$value / alpha
VaR <- -qnorm(alpha)  

num <- T * alpha *ES

set.seed(4652374)
Z2 <- numeric(N)   
Z4 <- numeric(N) 

for (j in 1:N) {
  Xt <- rnorm(T)
  Z2[j] <- sum(Xt * (Xt + VaR < 0)) / num + 1
  Z4[j] <- sum((alpha * (- VaR) + (Xt + VaR) * (Xt + VaR < 0)) / num) + 1
}

# 5% critical 
crit2 <- sort(Z2)[floor(N * (p))]
crit4 <- sort(Z4)[floor(N * (p))]

Z2_sim <- function(sigma) {
  Z <- numeric(N)
  VaR <- -qnorm(alpha, mean = (1 - sigma) * ES, sd = sigma) 
  ES <- -integrate(function(q) qnorm(q, mean = 0, sd = 1), lower = 0, upper = alpha)$value / alpha
  num <- T * alpha * ES
  set.seed(4652374)  
  for (j in 1:N) {
    Xt <- rnorm(T, 0, 1)
    Z[j] <- sum(Xt * (Xt + VaR < 0)) / num + 1
  }
  return(mean(Z))
}

Z4_sim <- function(sigma) {
  Z <- numeric(N)
  VaR <- -qnorm(alpha, mean = (1 - sigma) * ES, sd = sigma) 
  ES <- -integrate(function(q) qnorm(q, mean = 0, sd = 1), lower = 0, upper = alpha)$value / alpha
  num <- T * alpha * ES
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rnorm(T, 0, 1)
    Z[j] <- sum((alpha*(- VaR) + (Xt + VaR) * (Xt + VaR < 0)) / num) +1
  }
  return(mean(Z))
}


sigma_grid <- seq(0.93, 1.1, by = 0.005)
mu_grid <- (1-sigma_grid) * ES
v_pred <- -(mu_grid + sigma_grid * qnorm(alpha))
delta_v <- (v_pred-VaR)/v_pred
Z2_means <- sapply(sigma_grid, Z2_sim)
Z4_means <- sapply(sigma_grid, Z4_sim)

plot_data1 <- data.frame(
  x = delta_v,
  y = c(Z2_means, Z4_means),
  test = rep(c("E(Z2(e, v, X))", "E(Z4(e, v, X))"), each = length(sigma_grid))
)

ggplot(plot_data1, aes(x = x, y = y, color = test)) +
  geom_vline(xintercept = 0, linetype = "solid", color = "darkgrey") +
  geom_hline(yintercept = 0, linetype = "solid", color = "darkgrey") +
  geom_point(size = 2) +
  geom_hline(yintercept = crit2, linetype = "dashed", color = "red") +
  geom_hline(yintercept = crit4, linetype = "dashed", color = "blue") +
  scale_color_manual(values = c('red', 'blue')) +
  scale_y_continuous(limits = c(-0.8, 0.6)) +
  scale_x_continuous(limits = c(-0.15, 0.15)) +
  labs(
    x = expression((v-VaR)/v),
    y = "",
    color = "Middelværdi"
  ) + theme_minimal()

```


# Figur 2: 0.8*ES(F) = ES(P)
```{r}
Z2_sim <- function(sigma) {
  Z <- numeric(N)
  ES <- -0.8*integrate(function(q) qnorm(q, mean = 0, sd = 1), lower = 0, upper = alpha)$value / alpha
  VaR <- -qnorm(alpha, mean = (1-sigma) * ES, sd = sigma) 
  num <- T * alpha * ES
  set.seed(4652374)  
  for (j in 1:N) {
    Xt <- rnorm(T, 0, 1)
    Z[j] <- sum(Xt * (Xt + VaR < 0)) / num + 1
  }
  return(mean(Z))
}

Z4_sim <- function(sigma) {
  Z <- numeric(N)
  ES <- -0.8*integrate(function(q) qnorm(q, mean = 0, sd = 1), lower = 0, upper = alpha)$value / alpha
  VaR <- -qnorm(alpha, mean = (1-sigma) * ES, sd = sigma) 
  num <- T * alpha * ES
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rnorm(T, 0, 1)
    Z[j] <- sum((alpha * (- VaR) + (Xt + VaR) * (Xt + VaR < 0)) / num)+1
  }
  return(mean(Z))
}

sigma_grid <- seq(0.88, 1.05, by = 0.005)
mu_grid <- (1-sigma_grid) * ES
v_pred <- -(mu_grid + sigma_grid * qnorm(alpha))
delta_v <- (v_pred-VaR)/v_pred
Z2_means <- sapply(sigma_grid, Z2_sim)
Z4_means <- sapply(sigma_grid, Z4_sim)

plot_data2 <- data.frame(
  x = delta_v,
  y = c(Z2_means, Z4_means),
  test = rep(c("E(Z2(e*, v, X))", "E(Z4(e*, v, X))"), each = length(sigma_grid))
)

ggplot(plot_data2, aes(x = x, y = y, color = test)) +
  geom_vline(xintercept = 0, linetype = "solid", color = "darkgrey") +
  geom_hline(yintercept = 0, linetype = "solid", color = "darkgrey") +
  geom_point(size = 2) +
  geom_hline(yintercept = crit2, linetype = "dashed", color = "red") +
  geom_hline(yintercept = crit4, linetype = "dashed", color = "blue") +
  scale_color_manual(values = c('red', 'blue')) +
  scale_y_continuous(limits = c(-1.7, 0.1)) +
  scale_x_continuous(limits = c(-0.28, 0.05)) +
  labs(
    x = expression((v-VaR)/v),
    y = "",
    color = "Middelværdi"
  ) + theme_minimal()
```


# Stikprøvestørrelsens indvirkning på power

```{r}
Z2_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((Xt*(Xt < -VaR))/(T*alpha*ES))+1)
}

Z3_sim <- function(Xt, alpha, df) {
    T <- length(Xt)
    integer <- max(1,floor(T*alpha))
    lowestXt <- sort(Xt)[1:integer]
    ESestimator <- -sum(lowestXt)/integer
    integrale <- integrate(function(x) pbeta(1-x,T-integer,integer)*qt(x,df), 0, 1)$value
    EVanalytical <- -integrale*(T/integer)
    
    return(-(ESestimator/EVanalytical)+1) }
  

Z4_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((alpha*(-VaR)+(Xt+VaR)*(Xt + VaR < 0))/(T*alpha*ES))+1)
}

sim <- function(df0, df1, T){
  N <- 10^5
  alpha <- 0.025
  Z2_path <- matrix(0, N, 1); Z3_path <- matrix(0, N, 1); Z4_path <- matrix(0, N, 1)
  
  ES <- -integrate(function(q) qt(q, df0), 0, alpha)$value/alpha
  VaR <- -qt(alpha,df0)
  
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rt(T, df1)
    Z2_path[j] <- Z2_sim(Xt, VaR, ES, alpha)
    Z3_path[j] <- Z3_sim(Xt, alpha, df0)
    Z4_path[j] <- Z4_sim(Xt, VaR, ES, alpha)
  }
  return(list(Z2 = Z2_path, Z3 = Z3_path, Z4 = Z4_path))
}

simH0 <- sim(df0=100, df1=100, T = 10)
simH1 <- sim(df0=100, df1 = 5, T = 10)
  
ecdf(simH1$Z2)(quantile(simH0$Z2, probs = 0.05))
ecdf(simH1$Z3)(quantile(simH0$Z3, probs = 0.05))
ecdf(simH1$Z4)(quantile(simH0$Z4, probs = 0.05))

T_values <- c(10, 50, 100, 150, 250, 500, 750, 850, 1000)
power_data <- matrix(0,length(T_values),3)

Number <- seq(1,length(T_values), by = 1)
  
for(T_ in Number){
  simH0 <- sim(df0=100, df1=100, T_values[T_])
  simH1 <- sim(df0=100, df1 = 5, T_values[T_])
  
  power_data[T_,] <- c(ecdf(simH1$Z2)(quantile(simH0$Z2, probs = 0.05)),
                       ecdf(simH1$Z3)(quantile(simH0$Z3, probs = 0.05)),
                       ecdf(simH1$Z4)(quantile(simH0$Z4, probs = 0.05)))
}


plot_data1 <- data.frame(
  T_ = as.factor(rep(T_values, times = 3)),
  power = c(power_data[,1], power_data[,2], power_data[,3]),
  test = rep(c("Z2", "Z3", "Z4"), each = length(T_values))
)

ggplot(plot_data1, aes(x = T_, y = power, color = test, shape = test, group = test)) +
geom_vline(xintercept = 3, linetype = "solid", color = "darkgrey") +
  geom_point(size = 3) +
  geom_line() +
  scale_shape_manual(values = c(16, 17, 15)) +
  scale_color_manual(values = c('darkgreen', 'blue', 'red')) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    x = "Frihedsgrader",
    y = "Power",
    title = "Stikprøvestørrelsen",
    color = "Test Statistik",
    shape = "Test Statistik"
  ) + theme_minimal() + theme(panel.grid.major.x = element_blank())


```


```{r}
Z2_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((Xt*(Xt < -VaR))/(T*alpha*ES))+1)
}

sim <- function(df0, df1, T){
  N <- 10^5
  alpha <- 0.025
  Z2_path <- matrix(0, N, 1)
  
  ES <- -integrate(function(q) qt(q, df0), 0, alpha)$value/alpha
  VaR <- -qt(alpha,df0)
  
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rt(T, df1)
    Z2_path[j] <- Z2_sim(Xt, VaR, ES, alpha)
  }
  return(list(Z2 = Z2_path))
}

results <- data.frame()
T_values <- c(5, 10, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000)
df1_values <- c(3, 5, 7, 10, 15, 20, 30, 100)

for (T_ in T_values) {
  simH0 <- sim(df0 = 100, df1 = 100, T = T_)

  for (df1_ in df1_values) {
    simH1 <- sim(df0 = 100, df1 = df1_, T = T_)

    power_Z2 <- ecdf(simH1$Z2)(quantile(simH0$Z2, probs = 0.05))

    results <- rbind(
      results,
      data.frame(T = T_, df1 = df1_, test = "Z2", power = power_Z2)
    )
  }
}

# Plot
results$df1 <- factor(results$df1)
ggplot(results, aes(x = T, y = power, color = df1)) +
  geom_point(size = 2) +
  geom_line() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    title = "Test 2",
    x = "Stikprøvestørrelse T",
    y = "Power",
    color = "Teststatistik"
  ) +
  theme_minimal()
```

```{r}
Z3_sim <- function(Xt, alpha, df) {
    T <- length(Xt)
    integer <- max(1,floor(T*alpha))
    lowestXt <- sort(Xt)[1:integer]
    ESestimator <- -sum(lowestXt)/integer
    integrale <- integrate(function(x) pbeta(1-x,T-integer,integer)*qt(x,df), 0, 1)$value
    EVanalytical <- -integrale*(T/integer)
    
    return(-(ESestimator/EVanalytical)+1) }

sim <- function(df0, df1, T){
  N <- 10^5
  alpha <- 0.025
  Z3_path <- matrix(0, N, 1)
  
  ES <- -integrate(function(q) qt(q, df0), 0, alpha)$value/alpha
  VaR <- -qt(alpha,df0)
  
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rt(T, df1)
    Z3_path[j] <- Z3_sim(Xt, alpha, df0)
  }
  return(list(Z3 = Z3_path))
}

results2 <- data.frame()
T_values <- c(5, 10, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000)
df1_values <- c(3, 5, 7, 10, 15, 20, 30, 100)

for (T_ in T_values) {
  simH0 <- sim(df0 = 100, df1 = 100, T = T_)

  for (df1_ in df1_values) {
    simH1 <- sim(df0 = 100, df1 = df1_, T = T_)

    power_Z3 <- ecdf(simH1$Z3)(quantile(simH0$Z3, probs = 0.05))

    results2 <- rbind(
      results2,
      data.frame(T = T_, df1 = df1_, test = "Z3", power = power_Z3)
    )
  }
}

# Plot
results2$df1 <- factor(results2$df1)
ggplot(results2, aes(x = T, y = power, color = df1)) +
  geom_point(size = 2) +
  geom_line() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    title = "Test 3",
    x = "Stikprøvestørrelse T",
    y = "Power",
    color = "Teststatistik"
  ) +
  theme_minimal()
```


```{r}
Z4_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((alpha*(-VaR)+(Xt+VaR)*(Xt + VaR < 0))/(T*alpha*ES))+1)
}

sim <- function(df0, df1, T){
  N <- 10^5
  alpha <- 0.025
  Z4_path <- matrix(0, N, 1)
  
  ES <- -integrate(function(q) qt(q, df0), 0, alpha)$value/alpha
  VaR <- -qt(alpha,df0)
  
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rt(T, df1)
    Z4_path[j] <- Z4_sim(Xt, VaR, ES, alpha)
  }
  return(list(Z4 = Z4_path))
}

results3 <- data.frame()
T_values <- c(5, 10, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000)
df1_values <- c(3, 5, 7, 10, 15, 20, 30, 100)

for (T_ in T_values) {
  simH0 <- sim(df0 = 100, df1 = 100, T = T_)

  for (df1_ in df1_values) {
    simH1 <- sim(df0 = 100, df1 = df1_, T = T_)

    power_Z4 <- ecdf(simH1$Z4)(quantile(simH0$Z4, probs = 0.05))

    results3 <- rbind(
      results,
      data.frame(T = T_, df1 = df1_, test = "Z4", power = power_Z4)
    )
  }
}

# Plot
results3$df1 <- factor(results3$df1)
ggplot(results3, aes(x = T, y = power, color = df1)) +
  geom_point(size = 2) +
  geom_line() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    title = "Test 4",
    x = "Stikprøvestørrelse T",
    y = "Power",
    color = "Teststatistik"
  ) +
  theme_minimal()

```


# Ændring af antal frihedsgrader

```{r}
Z2_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((Xt*(Xt < -VaR))/(T*alpha*ES))+1)
}

Z3_sim <- function(Xt, alpha, df) {
    T <- length(Xt)
    integer <- floor(T*alpha)
    lowestXt <- sort(Xt)[1:integer]
    ESestimator <- -sum(lowestXt)/integer
    integrale <- integrate(function(x) pbeta(1-x,T-integer,integer)*qt(x,df), 0, 1)$value
    EVanalytical <- -integrale*(T/integer)
    
    return(-(ESestimator/EVanalytical)+1) }
  

Z4_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((alpha*(-VaR)+(Xt+VaR)*(Xt + VaR < 0))/(T*alpha*ES))+1)
}

sim <- function(df0, df1){
  T <- 250
  N <- 10^4
  alpha <- 0.025
  Z2_path <- matrix(0, N, 1); Z3_path <- matrix(0, N, 1); Z4_path <- matrix(0, N, 1)
  
  ES <- -integrate(function(q) qt(q, df0), 0, alpha)$value/alpha
  VaR <- -qt(alpha,df0)
  
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- rt(T, df1)
    Z2_path[j] <- Z2_sim(Xt, VaR, ES, alpha)
    Z3_path[j] <- Z3_sim(Xt, alpha, df0)
    Z4_path[j] <- Z4_sim(Xt, VaR, ES, alpha)
  }
  return(list(Z2 = Z2_path, Z3 = Z3_path, Z4 = Z4_path))
}


df_values <- c(3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20, 30, 50, 100, 10^4)
power_data <- matrix(0,length(df_values),3)

Number <- seq(1,length(df_values), by = 1)
  
for(df in Number){
  simH0 <- sim(df0=df_values[df], df1=df_values[df])
  simH1 <- sim(df0=df_values[df], df1 = 5)
  
  power_data[df,] <- c(ecdf(simH1$Z2)(quantile(simH0$Z2, probs = 0.05)),
                       ecdf(simH1$Z3)(quantile(simH0$Z3, probs = 0.05)),
                       ecdf(simH1$Z4)(quantile(simH0$Z4, probs = 0.05)))
}

plot_data1 <- data.frame(
  df = as.factor(rep(df_values, times = 3)),
  power = c(power_data[,1], power_data[,2], power_data[,3]),
  test = rep(c("Z2", "Z3", "Z4"), each = length(df_values))
)

ggplot(plot_data1, aes(x = df, y = power, color = test, shape = test, group = test)) +
geom_vline(xintercept = 3, linetype = "solid", color = "darkgrey") +
  geom_point(size = 3) +
  geom_line() +
  scale_shape_manual(values = c(16, 17, 15)) +
  scale_color_manual(values = c('darkgreen', 'blue', 'red')) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    x = "Frihedsgrader",
    y = "Power",
    title = "Ændring af frihedsgrader for Student t-fordeling",
    color = "Test Statistik",
    shape = "Test Statistik"
  ) + theme_minimal() + theme(panel.grid.major.x = element_blank())


```



# Ændring i volatiliteten

```{r}

Z2_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((Xt*(Xt < -VaR))/(T*alpha*ES))+1)
}

Z3_sim <- function(Xt, alpha, df, gam) {
    T <- length(Xt)
    integer <- floor(T*alpha)
    lowestXt <- sort(Xt)[1:integer]
    ESestimator <- -sum(lowestXt)/integer
    integrale <- integrate(function(x) pbeta(1-x,T-integer,integer)*gam*qt(x,  df), 0, 1)$value
    EVanalytical <- -integrale*(T/integer)
    
    return(-(ESestimator/EVanalytical)+1) }
  

Z4_sim <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((alpha*(-VaR)+(Xt+VaR)*(Xt + VaR < 0))/(T*alpha*ES))+1)
}

sim <- function(df, gam0, gam1){
  T <- 250
  N <- 10^4
  alpha <- 0.025
  Z2_path <- matrix(0, N, 1); Z3_path <- matrix(0, N, 1); Z4_path <- matrix(0, N, 1)
  
  ES <- -gam0*integrate(function(q) qt(q, df), 0, alpha)$value/alpha
  VaR <- -gam0*qt(alpha,df)
  
  set.seed(4652374)
  for (j in 1:N) {
    Xt <- gam1*rt(T, df) 
    Z2_path[j] <- Z2_sim(Xt, VaR, ES, alpha)
    Z3_path[j] <- Z3_sim(Xt, alpha, df, gam0)
    Z4_path[j] <- Z4_sim(Xt, VaR, ES, alpha)
  }
  return(list(Z2 = Z2_path, Z3 = Z3_path, Z4 = Z4_path))
}


gam_values <- seq(1.5, 1, by = -0.05)
power_data <- matrix(0,length(gam_values),3)

Number <- seq(1,length(gam_values), by = 1)
  
for(gam in Number){
  simH0 <- sim(df=5, gam0 = gam_values[gam], gam1 = gam_values[gam])
  simH1 <- sim(df=5, gam0 = gam_values[gam], gam1 = 1.45)
  
  power_data[gam,] <- c(ecdf(simH1$Z2)(quantile(simH0$Z2, probs = 0.05)),
                       ecdf(simH1$Z3)(quantile(simH0$Z3, probs = 0.05)),
                       ecdf(simH1$Z4)(quantile(simH0$Z4, probs = 0.05)))
}

plot_data2 <- data.frame(
  gam = rep(gam_values, times = 3),
  power = c(power_data[,1], power_data[,2], power_data[,3]),
  test = rep(c("Z2", "Z3", "Z4"), each = length(gam_values))
)

ggplot(plot_data2, aes(x = gam, y = power, color = test, shape = test, group = test)) +
geom_vline(xintercept = 1.45, linetype = "solid", color = "darkgrey") +
  geom_point(size = 3) +
  geom_line() +
  scale_shape_manual(values = c(16, 17, 15)) +
  scale_color_manual(values = c('darkgreen', 'blue', 'red')) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_x_reverse(breaks = c(seq(1.5, 0.9, by = -0.05))) +
  labs(
    x = "Gamma",
    y = "Power",
    title = "Ændring af gamma for Student t-fordeling",
    color = "Test Statistik",
    shape = "Test Statistik"
  ) + theme_minimal() + theme(panel.grid.major.x = element_blank(), 
                              panel.grid.minor.x = element_blank())


```

