---
title: "Historic"
author: "Daniel Riazi"
output: html_document
date: "2025-04-21"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rugarch)
library(fGarch)
library(ggplot2)
library(esback)
library(quantmod)
```

```{r}
Exceedance <- function(Xt, VaR){
  return(-sum((Xt + VaR < 0)))
}
  
Z2 <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((Xt*(Xt < -VaR))/(T*alpha*ES))+1)
}

Z4 <- function(Xt, VaR, ES, alpha) {
  T <- length(Xt)
  return(sum((alpha*(-VaR)+(Xt+VaR)*(Xt + VaR < 0))/(T*alpha*ES))+1)
}

```

# Eksperiment med refit undervejs

# Refit
```{r}
garch_path <- function(n.sim, n.start, omega, alpha1, beta1, df) {
  N <- n.sim + n.start
  Xt <- numeric(N)
  sigma2t <- numeric(N)
  Zt <- rstd(N, 0, 1, nu = df)
  
  # Initialværdi
  sigma2t[1] <- omega + beta1*omega/(1-alpha1-beta1)
  Xt[1] <- sqrt(sigma2t[1])*Zt[1]
  
  for (t in 2:N) {
    sigma2t[t] <- omega + alpha1*(Xt[t-1])^2 + beta1*sigma2t[t-1]
    Xt[t] <- sqrt(sigma2t[t])*Zt[t]
  }
  return(list(X = Xt, Xt = Xt[(n.start+1):N], sigma2 = sigma2t[(n.start+1):N]))
}

garch_next <- function(n.sim, omega, alpha1, beta1, df, X0, sigma2_0) {
  Xt <- numeric(n.sim)
  sigma2t <- numeric(n.sim)
  Zt <- rstd(n.sim, 0, 1, nu = df)
  
  # Initialværdi
  sigma2t[1] <- omega + alpha1*(X0)^2 + beta1*sigma2_0
  Xt[1] <- sqrt(sigma2t[1])*Zt[1]
  
  for (t in 2:n.sim) {
    sigma2t[t] <- omega + alpha1*(Xt[t-1])^2 + beta1*sigma2t[t-1]
    Xt[t] <- sqrt(sigma2t[t])*Zt[t]
  }
  return(list(Xt = Xt[1:n.sim], sigma2 = sigma2t[1:n.sim]))
}

N       <- 10^4
n_block <- 250
burnin  <- 1000
T <- 250
n <- 500

# HISTORISK SIMULATION
X_mat   <- matrix(0, N, n )
VaR_mat <- matrix(0, N, n )
VaR1_mat <- matrix(0, N, n )
ES_mat  <- matrix(0, N, n )

#set.seed(4652374)

#Simulation af data

for (i in 1:N) {
  
  b1 <- garch_path(n_block, burnin, omega = 0.01, alpha1 = 0.1, beta1 = 0.85, df = 5)

  b2 <- garch_next(n_block, omega = 0.03, alpha1 = 0.1, beta1 = 0.85, df = 5, tail(b1$Xt, 1), tail(b1$sigma2, 1))

  Xt_all    <- c(b1$Xt, b2$Xt)
  sigma_all <- c(sqrt(b1$sigma2), sqrt(b2$sigma2))

  VaR <- -sigma_all*qstd(alpha, 0, 1, nu = 5)
  VaR1 <- -sigma_all*qstd(0.01, 0, 1, nu = 5)
  ES  <- -sigma_all*(integrate(function(q) qstd(q, 0, 1, nu = 5), 0, alpha)$value / alpha)

  X_mat[i, ]   <- Xt_all
  VaR1_mat[i, ] <- VaR1
  VaR_mat[i, ] <- VaR
  ES_mat[i, ]  <- ES
}

# Historisk simulation

VaRHS_mat <- matrix(0, nrow = N, ncol = n)
VaR1HS_mat <- matrix(0, nrow = N, ncol = n)
ESHS_mat  <- matrix(0, nrow = N, ncol = n)

weights <- rep(1/T, T)

for (i in 1:N){
  for (m in (T+1):n){
    window <- X_mat[i,(m-T):(m-1)]
    
    sort_id <- order(window)  
    sorted_returns <- window[sort_id]
    sorted_weights <- weights[sort_id]
    
    cum_weights <- cumsum(sorted_weights)
    
    interpolation_VaR <- function(level) {
      j <- which(cum_weights >= level)[1]
      if (j == 1) {- sorted_returns[1]} 
      else {
      w1 <- cum_weights[j-1]; w2 <- cum_weights[j]
      r1 <- sorted_returns[j-1]; r2 <- sorted_returns[j]
      - (r1 + (level - w1) / (w2 - w1) * (r2 - r1))
      }
    }
    
    VaRHS_mat[i, m] <- interpolation_VaR(0.025)
    VaR1HS_mat[i, m] <- interpolation_VaR(0.01)
    
    VaR_index_alpha <- which(cum_weights >= 0.025)[1]
    cumulative_before <- sum(sorted_weights[1:(VaR_index_alpha-1)])
    adjusted_weight <- 0.025 - cumulative_before
    sorted_weights[VaR_index_alpha] <- 0.025 - cumulative_before
    
    ESHS_mat[i, m] <- -sum(sorted_returns[1:VaR_index_alpha]*sorted_weights[1:VaR_index_alpha])/0.025
  }
}

VaR_HS_tail_mat <- VaRHS_mat[,(T+1):n]
VaR1_HS_tail_mat <- VaR1HS_mat[,(T+1):n]
ES_HS_tail_mat <- ESHS_mat[,(T+1):n]
X_tail_mat <- X_mat[,(T+1):n]
var_tail_mat <- VaR_mat[,(T+1):n]
var1_tail_mat <- VaR1_mat[,(T+1):n]
es_tail_mat <- ES_mat[,(T+1):n]

# Udregning af test for den sande og prædikive model
  
sim <- function(alpha, X, VaR, VaR1, ES) {
  Z2_path <- matrix(0,N,1); Z4_path <- matrix(0,N,1); Exceedance_path <- matrix(0,N,1)
  
  for (i in 1:N) {
    Z2_path[i] <- Z2(X[i,], VaR[i,], ES[i,], alpha)
    Z4_path[i] <- Z4(X[i,], VaR[i,], ES[i,], alpha)
    Exceedance_path[i] <- Exceedance(X[i,], VaR1[i,])
  }
  return(list(Z2 = Z2_path, Z4 = Z4_path, Exceedance=Exceedance_path))
}

sim0_mat <- sim(0.025, X_tail_mat, var_tail_mat, var1_tail_mat, es_tail_mat)
sim1_mat <- sim(0.025, X_tail_mat, VaR_HS_tail_mat, VaR1_HS_tail_mat, ES_HS_tail_mat)

# sig-niveau
f <- function(p) {
  quantile(sim0_mat$Exceedance, probs = p, type = 1)
}

p_value <- seq(0.0, 0.1, length.out = 10000)
f_values <- sapply(p_value, f)
valid_p <- p_value[f_values == -6]
p <- round(max(valid_p), 4)
p

# Afvisningsrate
length(sim1_mat$Z2[sim1_mat$Z2<sort(sim0_mat$Z2)[floor(N*0.0402)]])/N 
length(sim1_mat$Z4[sim1_mat$Z4<sort(sim0_mat$Z4)[floor(N*0.0402)]])/N 
length(sim1_mat$Exceedance[sim1_mat$Exceedance<=sort(sim0_mat$Exceedance)[floor(N*0.0402)]])/N  

# Middelværdi plot for Z2
df_hist <- data.frame(
  Z2 = c(sim0_mat$Z2, sim1_mat$Z2),
  sim = rep(c("Z2_F", "Z2_P"), each = length(sim0_mat$Z2))
)

mean_F <- mean(sim0_mat$Z2) 
mean_P <- mean(sim1_mat$Z2)

histogram <- ggplot(df_hist, aes(x = Z2, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.1, color = "black") +
  scale_fill_manual(values = c("Z2_F" = "blue", "Z2_P" = "red")) + scale_x_continuous(limits = c(-3, 1.5)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z2", y = "Antal værdier", fill = "Simulation") +
  theme_minimal()+ theme(legend.position = "none")

histogram


# Middelværdi plot for Z4

df_hist <- data.frame(
  Z4 = c(sim0_mat$Z4, sim1_mat$Z4),
  sim = rep(c("Z4_F", "Z4_P"), each = length(sim0_mat$Z4))
)

mean_F <- mean(sim0_mat$Z4)
mean_P <- mean(sim1_mat$Z4)

histogram <- ggplot(df_hist, aes(x = Z4, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.05, color = "black") +
  scale_fill_manual(values = c("Z4_F" = "blue", "Z4_P" = "red")) + scale_x_continuous(limits = c(-1.5, 0.6)) +  geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z4", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram


# Middelværdi plot for VaR-testen

df_hist <- data.frame(
  VaR1 = c(sim0_mat$Exceedance, sim1_mat$Exceedance),
  sim = rep(c("VaR1_F", "VaR1_P"), each = length(sim0_mat$Exceedance))
)

mean_F <- mean(sim0_mat$Exceedance) 
mean_P <- mean(sim1_mat$Exceedance)

histogram <- ggplot(df_hist, aes(x = VaR1, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1, color = "black") +
  scale_fill_manual(values = c("VaR1_F" = "blue", "VaR1_P" = "red")) + scale_x_continuous(limits = c(-12.5, 0.5)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "VaR1", y = "Antal værdier", fill = "Simulation") +
  theme_minimal()+ theme(legend.position = "none")

histogram

```

# Plot 
```{r}
VaR_HS_tail <- tail(VaRHS_mat[10,],n-T)
ES_HS_tail <- tail(ESHS_mat[10,],n-T)
X_tail <- tail(X_mat[10,],n-T)
var_tail <- tail(VaR_mat[10,],n-T)
es_tail <- tail(ES_mat[10,],n-T)
  
plot <- data.frame(
  t        = 1:(n-T),
  returns  = X_tail,
  VaR      = -VaR_HS_tail,  
  ES       = -ES_HS_tail
)

ggplot(plot, aes(x = t)) +
  geom_line(aes(y = returns, color = "Afkast")) +
  geom_line(aes(y = VaR, color = "VaR"), linetype = "solid") +
  geom_line(aes(y = ES, color = "ES"), linetype = "solid") +
  scale_y_continuous(limits = c(-4.5, 4.5)) +
  scale_color_manual(
    name = "Størrelser",  
    values = c("Afkast"= "black","VaR" = "red", "ES" = "blue")) +
  labs(title = "Historisk Simulation",x = "t", y = "Xt") +
  theme_minimal() + theme(legend.position = "none")


X_tail <- tail(X_mat[10,],n)
var_tail <- tail(VaR_mat[10,],n)
es_tail <- tail(ES_mat[10,],n)
plot <- data.frame(
  t        = 1:(n),
  returns  = X_tail,
  VaR      = -var_tail,  
  ES       = -es_tail
)

ggplot(plot, aes(x = t)) +
  geom_rect(aes(xmin = 0, xmax = 250, ymin = -4.5, ymax = 4.5),
            fill = "lightblue", alpha = 0.01) +
  annotate("text", x = 125, y = 4.2, label = "In-sample", size = 5) +
  geom_line(aes(y = returns, color = "Afkast")) +
  geom_line(aes(y = VaR, color = "VaR"), linetype = "solid") +
  geom_line(aes(y = ES, color = "ES"), linetype = "solid") +
  scale_y_continuous(limits = c(-4.5, 4.5)) + 
  scale_color_manual(
    name = "Størrelser",  
    values = c("Afkast"= "black", "VaR" = "red", "ES" = "blue")) +
  labs(title = "Sande Datagenereringsproces", x = "t", y = "Xt") +
  theme_minimal() + theme(legend.position = "none")

```

# SANDSYNLIGHEDSVÆGTET HISTORISK SIMULATION
```{r}
# SVHS
VaR_PWHS <- matrix(0, nrow = N, ncol = n)
VaR1_PWHS <- matrix(0, nrow = N, ncol = n)
ES_PWHS  <- matrix(0, nrow = N, ncol = n)
 
lambda <- 0.99
weights <- (lambda ^ ((T-1):0)) * (1 - lambda)/ (1-lambda^T)

for (i in 1:N){
  for (m in (T+1):n){
    window <- X_mat[i,(m-T):(m-1)]
    
    sort_id <- order(window)  
    sorted_returns <- window[sort_id]
    sorted_weights <- weights[sort_id]
    
    cum_weights <- cumsum(sorted_weights)
    
    interpolation_VaR <- function(level) {
      j <- which(cum_weights >= level)[1]
      if (j == 1){ -sorted_returns[1]} else
      {
      w1 <- cum_weights[j-1]; w2 <- cum_weights[j]
      r1 <- sorted_returns[j-1]; r2 <- sorted_returns[j]
      - (r1 + (level - w1) / (w2 - w1) * (r2 - r1))
      }
    }
    
    VaR_PWHS[i, m] <- interpolation_VaR(0.025)
    VaR1_PWHS[i, m] <- interpolation_VaR(0.01)
    
    VaR_index_alpha <- which(cum_weights >= 0.025)[1]
    
    cumulative_before <- sum(sorted_weights[1:(VaR_index_alpha-1)])
    adjusted_weight <- 0.025 - cumulative_before
    sorted_weights[VaR_index_alpha] <- 0.025 - cumulative_before
    
    ES_PWHS[i, m] <- -sum(sorted_returns[1:VaR_index_alpha]*sorted_weights[1:VaR_index_alpha])/0.025
  }
}

VaR_HS_tail <- VaR_PWHS[,(T+1):n]
VaR1_HS_tail <- VaR1_PWHS[,(T+1):n]
ES_HS_tail <- ES_PWHS[,(T+1):n]
X_tail <- X_mat[,(T+1):n]
var_tail <- VaR_mat[,(T+1):n]
var1_tail <- VaR1_mat[,(T+1):n]
es_tail <- ES_mat[,(T+1):n]
  
# Udregning af test for den sande og prædikive model

sim <- function(alpha, X, VaR, VaR1, ES) {
  Z2_path <- matrix(0,N,1); Z4_path <- matrix(0,N,1); Exceedance_path <- matrix(0,N,1)
  
  for (i in 1:N) {
    Z2_path[i] <- Z2(X[i,], VaR[i,], ES[i,], alpha)
    Z4_path[i] <- Z4(X[i,], VaR[i,], ES[i,], alpha)
    Exceedance_path[i] <- Exceedance(X[i,], VaR1[i,])
  }
  return(list(Z2 = Z2_path, Z4 = Z4_path, Exceedance=Exceedance_path))
}

sim0 <- sim(0.025, X_tail, var_tail, var1_tail, es_tail)
sim1 <- sim(0.025, X_tail, VaR_HS_tail, VaR1_HS_tail, ES_HS_tail)

# sig-niveau

f <- function(p) {
  quantile(sim0$Exceedance, probs = p, type = 1)
}

p_value <- seq(0.03, 0.06, length.out = 10000)
f_values <- sapply(p_value, f)
valid_p <- p_value[f_values == -6]
p <- round(max(valid_p), 4)
p

# Afvisningsrate
length(sim1$Z2[sim1$Z2<sort(sim0$Z2)[floor(N*0.0402)]])/N 
length(sim1$Z4[sim1$Z4<sort(sim0$Z4)[floor(N*0.0402)]])/N 
length(sim1$Exceedance[sim1$Exceedance<=sort(sim0$Exceedance)[floor(N*0.0402)]])/N 

# PWHS sti
stiVaR_HS_tail <- tail(VaR_PWHS[10,],n-T)
stiES_HS_tail <- tail(ES_PWHS[10,],n-T)
stiX_tail <- tail(X_mat[10,],n-T)
  
plot <- data.frame(
  t        = 1:(n-T),
  returns  = stiX_tail,
  VaR      = -stiVaR_HS_tail,  
  ES       = -stiES_HS_tail
)

ggplot(plot, aes(x = t)) +
  geom_line(aes(y = returns, color = "Afkast")) +
  geom_line(aes(y = VaR, color = "VaR"), linetype = "solid") +
  geom_line(aes(y = ES, color = "ES"), linetype = "solid") +
  scale_y_continuous(limits = c(-4.5, 4.5)) +
  scale_color_manual( name = "Størrelser", values = c("Afkast" = "black", "VaR" = "red", "ES" = "blue")) + labs(title = "Sandsynlighedsvægtet Historisk Simulation", x = "t", y = "Xt") +
  theme_minimal() + theme(legend.position = "none")

# Middelværdi plot for Z2
df_hist <- data.frame(
  Z2 = c(sim0$Z2, sim1$Z2),
  sim = rep(c("Z2_F", "Z2_P"), each = length(sim0$Z2))
)

mean_F <- mean(sim0$Z2) 
mean_P <- mean(sim1$Z2)

histogram <- ggplot(df_hist, aes(x = Z2, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.1, color = "black") +
  scale_fill_manual(values = c("Z2_F" = "blue", "Z2_P" = "red")) + scale_x_continuous(limits = c(-3, 1.5)) +  geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z2", y = "Antal værdier",fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram



# Middelværdi plot for Z4

df_hist <- data.frame(
  Z4 = c(sim0$Z4, sim1$Z4),
  sim = rep(c("Z4_F", "Z4_P"), each = length(sim0$Z4))
)

mean_F <- mean(sim0$Z4) 
mean_P <- mean(sim1$Z4)

histogram <- ggplot(df_hist, aes(x = Z4, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.05, color = "black") +
  scale_fill_manual(values = c("Z4_F" = "blue", "Z4_P" = "red")) + scale_x_continuous(limits = c(-1.5, 0.6)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z4", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram


# Middelværdi plot for VaR-testen

df_hist <- data.frame(
  VaR1 = c(sim0$Exceedance, sim1$Exceedance),
  sim = rep(c("VaR1_F", "VaR1_P"), each = length(sim0$Exceedance))
)

mean_F <- mean(sim0$Exceedance) 
mean_P <- mean(sim1$Exceedance)

histogram <- ggplot(df_hist, aes(x = VaR1, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1, color = "black") +
  scale_fill_manual(values = c("VaR1_F" = "blue", "VaR1_P" = "red")) + scale_x_continuous(limits = c(-12.5, 0.5)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "VaR1", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram


```

### Normale eksperiment uden ændring i markedsdynamik undervejs

```{r}
garch_path <- function(n.sim, n.start, omega, alpha1, beta1, df) {
  N <- n.sim + n.start
  Xt <- numeric(N)
  sigma2t <- numeric(N)
  Zt <- rstd(N, 0, 1, nu = df)
  
  # Initialværdi
  sigma2t[1] <- omega + beta1*omega/(1-alpha1-beta1)
  Xt[1] <- sqrt(sigma2t[1])*Zt[1]
  
  for (t in 2:N) {
    sigma2t[t] <- omega + alpha1*(Xt[t-1])^2 + beta1*sigma2t[t-1]
    Xt[t] <- sqrt(sigma2t[t])*Zt[t]
  }
  return(list(X = Xt, Xt = Xt[(n.start+1):N], sigma2 = sigma2t[(n.start+1):N]))
}

df  <- 5        
alpha <- 0.025
alpha1 <- 0.1   
beta1 <- 0.85   
omega <- 0.01

N <- 10^4
n <- 500 
T <- 250
burnin <- 1000

# Simulation af data

  X <- matrix(0,N,n); var <- matrix(0,N,n); var1 <- matrix(0,N,n); es <- matrix(0,N,n)
  #set.seed(4652374)
  for (i in 1:N) {
    path_sim <- garch_path(n, burnin, omega, alpha1, beta1, df)
    X[i,] <- as.numeric(path_sim$Xt)
    sigma <- as.numeric(sqrt(path_sim$sigma2))
    var[i,] <- -sigma*qstd(alpha, 0, 1, df)
    var1[i,] <- -sigma*qstd(0.01, 0, 1, df)
    es[i,] <- -sigma*(integrate(function(q) qstd(q, 0, 1, df), 0, alpha)$value/alpha)
  }

VaR_HS <- matrix(0, nrow = N, ncol = n)
VaR1_HS <- matrix(0, nrow = N, ncol = n)
ES_HS  <- matrix(0, nrow = N, ncol = n)

# HISTORISK SIMULATION

weights <- rep(1/T, T)

for (i in 1:N){
  for (m in (T+1):n){
    window <- X[i,(m-T):(m-1)]
    
    sort_id <- order(window)  
    sorted_returns <- window[sort_id]
    sorted_weights <- weights[sort_id]
    
    cum_weights <- cumsum(sorted_weights)
    
    interpolation_VaR <- function(level) {
      j <- which(cum_weights >= level)[1]
      if (j == 1) {-sorted_returns[1]} else {
      w1 <- cum_weights[j-1]; w2 <- cum_weights[j]
      r1 <- sorted_returns[j-1]; r2 <- sorted_returns[j]
      - (r1 + (level - w1) / (w2 - w1) * (r2 - r1))
      }
    }
    
    VaR_HS[i, m] <- interpolation_VaR(0.025)
    VaR1_HS[i, m] <- interpolation_VaR(0.01)
    
    VaR_index_alpha <- which(cum_weights >= 0.025)[1]
    cumulative_before <- sum(sorted_weights[1:(VaR_index_alpha-1)])
    adjusted_weight <- 0.025 - cumulative_before
    sorted_weights[VaR_index_alpha] <- 0.025 - cumulative_before
    
    ES_HS[i, m] <- -sum(sorted_returns[1:VaR_index_alpha]*sorted_weights[1:VaR_index_alpha])/0.025
  }
}

VaR_HS_tail <- VaR_HS[,(T+1):n]
VaR1_HS_tail <- VaR1_HS[,(T+1):n]
ES_HS_tail <- ES_HS[,(T+1):n]
X_tail <- X[,(T+1):n]
var_tail <- var[,(T+1):n]
var1_tail <- var1[,(T+1):n]
es_tail <- es[,(T+1):n]
  
# Udregning af test for den sande og prædikive model

sim <- function(alpha, X, VaR, VaR1, ES) {
  Z2_path <- matrix(0,N,1); Z4_path <- matrix(0,N,1); Exceedance_path <- matrix(0,N,1)
  
  for (i in 1:N) {
    Z2_path[i] <- Z2(X[i,], VaR[i,], ES[i,], alpha)
    Z4_path[i] <- Z4(X[i,], VaR[i,], ES[i,], alpha)
    Exceedance_path[i] <- Exceedance(X[i,], VaR1[i,])
  }
  return(list(Z2 = Z2_path, Z4 = Z4_path, Exceedance=Exceedance_path))
}

sim0 <- sim(0.025, X_tail, var_tail, var1_tail, es_tail)
sim1 <- sim(0.025, X_tail, VaR_HS_tail, VaR1_HS_tail, ES_HS_tail)

# sig-niveau

f <- function(p) {
  quantile(sim0$Exceedance, probs = p, type = 1)
}

p_value <- seq(0.03, 0.06, length.out = 10000)
f_values <- sapply(p_value, f)
valid_p <- p_value[f_values == -6]
p <- round(max(valid_p), 4)
p

# Afvisningsrate
length(sim1$Z2[sim1$Z2<sort(sim0$Z2)[floor(N*0.0398)]])/N 
length(sim1$Z4[sim1$Z4<sort(sim0$Z4)[floor(N*0.0398)]])/N 
length(sim1$Exceedance[sim1$Exceedance<=sort(sim0$Exceedance)[floor(N*0.0398)]])/N  

# Middelværdi plot for Z2
df_hist <- data.frame(
  Z2 = c(sim0$Z2, sim1$Z2),
  sim = rep(c("Z2_F", "Z2_P"), each = length(sim0$Z2))
)

mean_F <- mean(sim0$Z2) 
mean_P <- mean(sim1$Z2)

histogram <- ggplot(df_hist, aes(x = Z2, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.1, color = "black") +
  scale_fill_manual(values = c("Z2_F" = "blue", "Z2_P" = "red")) + scale_x_continuous(limits = c(-3, 1.5)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z2", y = "Antal værdier", fill = "Simulation") +
  theme_minimal()+ theme(legend.position = "none")

histogram


# Middelværdi plot for Z4

df_hist <- data.frame(
  Z4 = c(sim0$Z4, sim1$Z4),
  sim = rep(c("Z4_F", "Z4_P"), each = length(sim0$Z4))
)

mean_F <- mean(sim0$Z4)
mean_P <- mean(sim1$Z4)

histogram <- ggplot(df_hist, aes(x = Z4, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.05, color = "black") +
  scale_fill_manual(values = c("Z4_F" = "blue", "Z4_P" = "red")) + scale_x_continuous(limits = c(-1, 0.6)) +  geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z4", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram


# Middelværdi plot for VaR-testen

df_hist <- data.frame(
  VaR1 = c(sim0$Exceedance, sim1$Exceedance),
  sim = rep(c("VaR1_F", "VaR1_P"), each = length(sim0$Exceedance))
)

mean_F <- mean(sim0$Exceedance) 
mean_P <- mean(sim1$Exceedance)

histogram <- ggplot(df_hist, aes(x = VaR1, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1, color = "black") +
  scale_fill_manual(values = c("VaR1_F" = "blue", "VaR1_P" = "red")) + scale_x_continuous(limits = c(-10.5, 0.5)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "VaR1", y = "Antal værdier", fill = "Simulation") +
  theme_minimal()+ theme(legend.position = "none")

histogram

```


# Plot 
```{r}
VaR_HS_tail <- tail(VaR_HS[8,],n-T)
ES_HS_tail <- tail(ES_HS[8,],n-T)
X_tail <- tail(X[8,],n-T)
var_tail <- tail(var[8,],n-T)
es_tail <- tail(es[8,],n-T)
  
plot <- data.frame(
  t        = 1:(n-T),
  returns  = X_tail,
  VaR      = -VaR_HS_tail,  
  ES       = -ES_HS_tail
)

ggplot(plot, aes(x = t)) +
  geom_line(aes(y = returns, color = "Afkast")) +
  geom_line(aes(y = VaR, color = "VaR"), linetype = "solid") +
  geom_line(aes(y = ES, color = "ES"), linetype = "solid") +
  scale_y_continuous(limits = c(-1.8, 1.6)) +
  scale_color_manual(name = "Størrelser", values = c("Afkast" = "black", "VaR" = "red", "ES" = "blue")) +
  labs( title = "Historisk Simulation", x = "t", y = "Xt") +
  theme_minimal() + theme(legend.position = "none")


plot <- data.frame(
  t        = 1:(n-T),
  returns  = X_tail,
  VaR      = -var_tail,  
  ES       = -es_tail
)

ggplot(plot, aes(x = t)) +
  geom_line(aes(y = returns, color = "Afkast")) +
  geom_line(aes(y = VaR, color = "VaR"), linetype = "solid") +
  geom_line(aes(y = ES, color = "ES"), linetype = "solid") +
  scale_y_continuous(limits = c(-1.8, 1.6)) +
  scale_color_manual(name = "Størrelser", values = c("Afkast" = "black", "VaR" = "red", "ES" = "blue")) + labs(title = "Sande Datagenereringsproces", x = "t", y = "Xt") +
  theme_minimal() + theme(legend.position = "none")

```


# SANDSYNLIGHEDSVÆGTET HISTORISK SIMULATION

```{r}
# SVHS
VaR_HS <- matrix(0, nrow = N, ncol = n)
VaR1_HS <- matrix(0, nrow = N, ncol = n)
ES_HS  <- matrix(0, nrow = N, ncol = n)
 
lambda <- 0.99
weights <- (lambda ^ ((T-1):0)) * (1 - lambda)/ (1-lambda^T)

for (i in 1:N){
  for (m in (T+1):n){
    window <- X[i,(m-T):(m-1)]
    
    sort_id <- order(window)  
    sorted_returns <- window[sort_id]
    sorted_weights <- weights[sort_id]
    
    cum_weights <- cumsum(sorted_weights)
    
    interpolation_VaR <- function(level) {
      j <- which(cum_weights >= level)[1]
      if (j == 1) {-sorted_returns[1]} else {
      w1 <- cum_weights[j-1]; w2 <- cum_weights[j]
      r1 <- sorted_returns[j-1]; r2 <- sorted_returns[j]
      - (r1 + (level - w1) / (w2 - w1) * (r2 - r1))
      }
    }
    
    VaR_HS[i, m] <- interpolation_VaR(0.025)
    VaR1_HS[i, m] <- interpolation_VaR(0.01)
    
    VaR_index_alpha <- which(cum_weights >= 0.025)[1]
    
    cumulative_before <- sum(sorted_weights[1:(VaR_index_alpha-1)])
    adjusted_weight <- 0.025 - cumulative_before
    sorted_weights[VaR_index_alpha] <- 0.025 - cumulative_before
    
    ES_HS[i, m] <- -sum(sorted_returns[1:VaR_index_alpha]*sorted_weights[1:VaR_index_alpha])/0.025
  }
}

VaR_HS_tail <- VaR_HS[,(T+1):n]
VaR1_HS_tail <- VaR1_HS[,(T+1):n]
ES_HS_tail <- ES_HS[,(T+1):n]
X_tail <- X[,(T+1):n]
var_tail <- var[,(T+1):n]
var1_tail <- var1[,(T+1):n]
es_tail <- es[,(T+1):n]
  
# Udregning af test for den sande og prædikive model

sim <- function(alpha, X, VaR, VaR1, ES) {
  Z2_path <- matrix(0,N,1); Z4_path <- matrix(0,N,1); Exceedance_path <- matrix(0,N,1)
  
  for (i in 1:N) {
    Z2_path[i] <- Z2(X[i,], VaR[i,], ES[i,], alpha)
    Z4_path[i] <- Z4(X[i,], VaR[i,], ES[i,], alpha)
    Exceedance_path[i] <- Exceedance(X[i,], VaR1[i,])
  }
  return(list(Z2 = Z2_path, Z4 = Z4_path, Exceedance=Exceedance_path))
}

sim0 <- sim(0.025, X_tail, var_tail, var1_tail, es_tail)
sim1 <- sim(0.025, X_tail, VaR_HS_tail, VaR1_HS_tail, ES_HS_tail)

# sig-niveau

f <- function(p) {
  quantile(sim0$Exceedance, probs = p, type = 1)
}

p_value <- seq(0.03, 0.06, length.out = 10000)
f_values <- sapply(p_value, f)
valid_p <- p_value[f_values == -6]
p <- round(max(valid_p), 4)
p

# Afvisningsrate
length(sim1$Z2[sim1$Z2<sort(sim0$Z2)[floor(N*0.0398)]])/N 
length(sim1$Z4[sim1$Z4<sort(sim0$Z4)[floor(N*0.0398)]])/N 
length(sim1$Exceedance[sim1$Exceedance<=sort(sim0$Exceedance)[floor(N*0.0398)]])/N 

# PWHS sti
stiVaR_HS_tail <- tail(VaR_HS[8,],n-T)
stiES_HS_tail <- tail(ES_HS[8,],n-T)
stiX_tail <- tail(X[8,],n-T)
  
plot <- data.frame(
  t        = 1:(n-T),
  returns  = stiX_tail,
  VaR      = -stiVaR_HS_tail,  
  ES       = -stiES_HS_tail
)

ggplot(plot, aes(x = t)) +
  geom_line(aes(y = returns, color = "Afkast")) +
  geom_line(aes(y = VaR, color = "VaR"), linetype = "solid") +
  geom_line(aes(y = ES, color = "ES"), linetype = "solid") +
  scale_y_continuous(limits = c(-1.8, 1.6)) +
  scale_color_manual(name = "Størrelser", values = c("Afkast" = "black","VaR" = "red","ES" = "blue")) + labs(title = "Sandsynlighedsvægtet Historisk Simulation", x = "t", y = "Xt") +
  theme_minimal() + theme(legend.position = "none")

# Middelværdi plot for Z2
df_hist <- data.frame(
  Z2 = c(sim0$Z2, sim1$Z2),
  sim = rep(c("Z2_F", "Z2_P"), each = length(sim0$Z2))
)

mean_F <- mean(sim0$Z2) 
mean_P <- mean(sim1$Z2)

histogram <- ggplot(df_hist, aes(x = Z2, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.1, color = "black") +
  scale_fill_manual(values = c("Z2_F" = "blue", "Z2_P" = "red")) + scale_x_continuous(limits = c(-3, 1.5)) +  geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z2", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram



# Middelværdi plot for Z4

df_hist <- data.frame(
  Z4 = c(sim0$Z4, sim1$Z4),
  sim = rep(c("Z4_F", "Z4_P"), each = length(sim0$Z4))
)

mean_F <- mean(sim0$Z4) 
mean_P <- mean(sim1$Z4)

histogram <- ggplot(df_hist, aes(x = Z4, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 0.05, color = "black") +
  scale_fill_manual(values = c("Z4_F" = "blue", "Z4_P" = "red")) + scale_x_continuous(limits = c(-1, 0.6)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "Z4", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram


# Middelværdi plot for VaR-testen

df_hist <- data.frame(
  VaR1 = c(sim0$Exceedance, sim1$Exceedance),
  sim = rep(c("VaR1_F", "VaR1_P"), each = length(sim0$Exceedance))
)

mean_F <- mean(sim0$Exceedance) 
mean_P <- mean(sim1$Exceedance)

histogram <- ggplot(df_hist, aes(x = VaR1, fill = sim)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1, color = "black") +
  scale_fill_manual(values = c("VaR1_F" = "blue", "VaR1_P" = "red")) + scale_x_continuous(limits = c(-10.5, 0.5)) + geom_vline(xintercept = mean_F, color = "blue", linetype = "solid", size = 1) +
  geom_vline(xintercept = mean_P, color = "red", linetype = "solid", size = 1) +
  labs(title = "", x = "VaR1", y = "Antal værdier", fill = "Simulation") +
  theme_minimal() + theme(legend.position = "none")

histogram


```


